# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: John O'Donovan
email: jod@cs.ucsb.edu
description: > # this means to ignore newlines until "baseurl:"
  I am an associate research scientist at the Computer Science dept., UCSB. My research background is in AI, with focus on recommender systems. I have a particular interest in human-computer interaction aspects of these systems --for example, learning how an interaction design impacts human trust in an algorithm over time. I am also a co-founder and CTO of Siras Systems Inc., providers of personalized educational planning and reporting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
